target1:
	@ echo "Hello there!"
	@ echo "if you wish to see how it works:"
	@ echo " - run: 'make -f m_how_it_works.mk'"
	@ echo "if you wish to run all the test cases:"
	@ echo " - run: 'make -f m_test_it.mk'"
